global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'inventory-api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s

  - job_name: 'inventory-service'
    static_configs:
      - targets: ['inventory-service:8081']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s

  - job_name: 'sync-service'
    static_configs:
      - targets: ['sync-service:8082']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
